spring:
  application:
    name: folder-sync

  datasource:
    url: jdbc:h2:file:./data/syncdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

# Configuration spécifique à l'application
sync:
  default-interval: 7200000  # 2 heures en millisecondes
  max-concurrent-syncs: 3
  chunk-size: 8192  # Taille buffer pour copie de fichiers (8KB)
